name: Deploy to AWS ElasticBean
on:
  workflow_dispatch
# uncomment when ready for CICD
#  push:
#    branches:
#      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Deployment Package
        run: cd aws; zip -r deploy.zip docker-compose.prod.yml .platform/ .ebextensions/
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: pretty-estimate-new
          environment_name: Pretty-estimate-new-env
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: eu-west-2
          deployment_package: aws/deploy.zip
